In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat) #2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,4))   #no. of rows and no. of columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,5,10) #evenly spaced numbers between mentioned #1D array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5,100) #3rd argument is the no. of points you want

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [17]:
np.eye(4) # returns a sqaure matrix 2D array 1 is present diagonally

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)
#this is gonna create an array of the given shape you passs in 
# of uniform distribution from 0 to 1.

array([0.05525245, 0.76768238, 0.59990443, 0.4736343 , 0.5184987 ])

In [19]:
np.random.rand(5,5)

array([[0.78781126, 0.29613242, 0.42932696, 0.72804677, 0.1582372 ],
       [0.97320217, 0.76424102, 0.89127605, 0.62207215, 0.73941015],
       [0.95540941, 0.61942799, 0.22094494, 0.47915326, 0.97168207],
       [0.19617743, 0.54298545, 0.778244  , 0.60826163, 0.72164641],
       [0.81884123, 0.00430414, 0.3559109 , 0.91098136, 0.41156686]])

In [20]:
np.random.randn(5)
# this return no. from standard normal distribution centred around zero

array([ 0.22798299, -0.43880967, -2.65368979,  0.17345093, -0.56999121])

In [21]:
np.random.randn(5,4) # no need of tuple for dimension

array([[-0.20015175, -0.87276326, -1.46496858, -0.37209429],
       [ 0.12187079,  1.65275692, -1.62434881, -1.28499641],
       [-1.19507588,  1.28709085, -1.39910034,  0.71331395],
       [-0.34734422,  1.74504656, -1.06459631, -0.71266232],
       [ 1.30859236, -0.75174916,  1.38197373,  0.36324338]])

In [22]:
np.random.randint(0,10)

8

In [23]:
np.random.randint(0,100,10) # no. of integers

array([35, 91,  4, 83, 11, 36, 47, 25, 46, 81])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([34,  6,  0, 17, 11, 44, 29,  9, 30,  0])

In [28]:
arr.reshape(5,5) #reshapes the array as the matrix
# the product of the  arguments should equal to the no. of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

44

In [30]:
ranarr.min()

0

In [31]:
ranarr.mean()

18.0

In [32]:
ranarr.argmax()

5

In [33]:
ranarr.argmin()

2

In [34]:
arr.shape


(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int32')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

8

In [41]:
# indices and selections

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[5]

5

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr = arr[0:6]

In [54]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:] = 99

In [56]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy = arr.copy()

In [59]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
# indexing 2D array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
 arr_2d[0][0]

5

In [66]:
arr_2d[1][2]

30

In [67]:
arr_2d[1][1]

25

In [68]:
arr_2d[2][2]

45

In [69]:
# another notation

In [70]:
arr_2d[1,1]

25

In [71]:
arr_2d[2,2]

45

In [72]:
arr>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [73]:
bool_arr = arr>5

In [74]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [75]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [76]:
arr = np.arange(0,11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
bool_arr = arr>5

In [79]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [80]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [82]:
arr_2d = np.arange(50).reshape(5,10)

In [83]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
arr_2d[2,1:6]

array([21, 22, 23, 24, 25])

In [85]:
arr_2d[arr_2d%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [86]:
arr_2d[1,3:6]

array([13, 14, 15])

In [87]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [88]:
# NUMPY OPERATIONS

In [89]:
arr = np.arange(0,11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr/arr

C:\Users\KAUSTU~1\AppData\Local\Temp/ipykernel_18808/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [94]:
1/arr

C:\Users\KAUSTU~1\AppData\Local\Temp/ipykernel_18808/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [95]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [96]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [97]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
# Universal Operations

In [99]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [100]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [101]:
arr.max()

10

In [102]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [103]:
np.log(arr)

C:\Users\KAUSTU~1\AppData\Local\Temp/ipykernel_18808/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [104]:
# NUMPY EXCERCISES

In [105]:
mat = np.arange(1,26).reshape(5,5)

In [106]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:
arr_sum = np.array(mat.sum(axis=0))

In [108]:
arr_sum

array([55, 60, 65, 70, 75])