In [4]:
import cv2

In [3]:
# !pip install opencv

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv


In [13]:
img = cv2.imread("C:\\Users\\kaustubh kapare\\Downloads\\mclaren.jpg",1)

In [14]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[121 120 122]
  [121 120 122]
  [121 120 122]
  ...
  [125 127 128]
  [126 128 129]
  [126 128 129]]

 [[121 120 122]
  [121 120 122]
  [121 120 122]
  ...
  [126 128 129]
  [125 127 128]
  [125 127 128]]

 [[120 119 121]
  [121 120 122]
  [121 120 122]
  ...
  [126 128 129]
  [125 127 128]
  [125 127 128]]]


In [15]:
resized = cv2.resize(img,(600,600))

In [16]:
# cv2.imshow("Wine",resized)

In [6]:
# cv2.waitKey(2000)

In [7]:
# cv2.destroyAllWindows()

In [8]:
# type(resized)

In [9]:
# print(img.shape)

In [10]:
# print(resized.shape)

In [12]:
import numpy as np
# import cv2

face_cascade = cv2.CascadeClassifier('C:/Users/kaustubh kapare/Downloads/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('C:/Users/kaustubh kapare/Downloads/haarcascade_eye.xml')

img = cv2.imread('C:/Users/kaustubh kapare/Downloads/mclaren.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(img)
print(img.shape)
print(gray)

faces = face_cascade.detectMultiScale(gray, 1.3, 5) 

for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[121 120 122]
  [121 120 122]
  [121 120 122]
  ...
  [125 127 128]
  [126 128 129]
  [126 128 129]]

 [[121 120 122]
  [121 120 122]
  [121 120 122]
  ...
  [126 128 129]
  [125 127 128]
  [125 127 128]]

 [[120 119 121]
  [121 120 122]
  [121 120 122]
  ...
  [126 128 129]
  [125 127 128]
  [125 127 128]]]
(2048, 1686, 3)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [121 121 121 ... 127 128 128]
 [121 121 121 ... 128 127 127]
 [120 121 121 ... 128 127 127]]


In [5]:
# import cv2 
# video = cv2.VideoCapture(0)
# video.release

In [2]:
import cv2 as cv

In [3]:
img = cv.imread("C:/Users/kaustubh kapare/Downloads/banglore.jpg")

In [4]:
print(img)

[[[107  82  86]
  [107  82  86]
  [114  89  93]
  ...
  [ 11  13  23]
  [ 10  12  22]
  [  9  11  21]]

 [[111  86  90]
  [109  84  88]
  [113  88  92]
  ...
  [  9  11  21]
  [  9  11  21]
  [ 10  12  22]]

 [[105  82  86]
  [104  81  85]
  [107  84  88]
  ...
  [  7   9  19]
  [  9  11  21]
  [ 12  14  24]]

 ...

 [[ 94 105 103]
  [ 87  98  96]
  [ 73  82  79]
  ...
  [ 39  45  56]
  [ 42  48  59]
  [ 44  50  61]]

 [[ 92 105 103]
  [ 85  98  96]
  [ 73  84  81]
  ...
  [ 41  47  60]
  [ 42  50  63]
  [ 44  52  65]]

 [[ 90 103 101]
  [ 83  96  94]
  [ 72  83  80]
  ...
  [ 42  48  61]
  [ 43  50  65]
  [ 46  53  68]]]


In [11]:
# cv.imshow("banglore",img)

In [5]:
# cv.waitKey(0)

In [6]:
# capture = cv.VideoCapture()
# # we use a whiel loop to read a video frame frame 
# while True:
# #        isTrue, frame = capture.read()
# cv2.imageshow("video",frame)                   #imageshow("Video",frame)
# cv.waitKey(0)

In [1]:
import cv2 as cv
video = cv.VideoCapture(0)
while True:
    isTrue, frame = video.read()
    cv.imshow("video",frame)
    if cv.waitKey(20) &  0xFF== ord('d'):
        break
video.release()
cv.destroyAllWindows()
    
# check, frame = video.read()
# print(check)
# print(frame)
# time.sleep(3)
# video.release()

In [1]:
import cv2 as cv
img = cv.imread("C:/Users/kaustubh kapare/Downloads/banglore.jpg")
cv.imshow("banglore",img)
cv.waitKey(0)

-1