In [4]:
# def random_pipe():
#     pipe = []
#     pipe.append("a")
#     pipe.append("b")
#     print(pipe)

In [5]:
# random_pipe()

['a', 'b']


In [ ]:
def prime_num(num):
    if num <2:
        return 0
    my_list = [2]
    x = 3
    for y in range(3,num,2):
        while y <= x and x <= num:
            if x%y != 0:
                my_list.append(x)
                x+=2
    print(my_list)

In [130]:
# List = []
# a = (20,30)
# b = (50,60)
# List.append(list(a))
# List.append(list(b))

In [131]:
# print(List)

[[20, 30], [50, 60]]


In [133]:
# List[0][0]

20

In [108]:
#  print(index(tuple(k))

In [113]:
# def move(tup):
#     for x in tup:
#         pass

In [114]:
# ans = map(move,result)

In [115]:
# print(ans)

In [117]:
# a = [[[23,10],[22,40]]]

In [120]:
# a[0][0][0]

In [53]:
List = [0,1,2,3]

In [54]:
for List[-2] in List:
    print(List)
    print(List[-2])

[0, 1, 0, 3]
0
[0, 1, 1, 3]
1
[0, 1, 1, 3]
1
[0, 1, 3, 3]
3


In [55]:
birds = {1,2,3,4}
birds.update("5")

In [56]:
birds

{1, 2, 3, 4, '5'}

In [57]:
birds.add("6")

In [60]:
birds

{1, 2, 3, 4, '5', '6'}

In [62]:
import pandas as pd

In [63]:
mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]

In [64]:
# df = pd.read_csv("Somefilenamewithlocation.csv")
# dataset = pd.Dataframe(df.data)
# dataset.columns = df.feature_names
# print(dataset.head)
# dataset.head()

In [65]:
# X = dataset.iloc[:,:-1]
# y = dataset.iloc[:,-1]

In [67]:
df = pd.DataFrame(mydict)

In [68]:
df

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [84]:
df.iloc[:-1]

a    b    c    d
0    1    2    3    4
1  100  200  300  400

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
import numpy as np
from sklearn.model_selection import train_test_split
x,y = np.arange(10).reshape((5,2)),range(5)

In [55]:
x,y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 range(0, 5))

In [45]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [46]:
list(y)

[0, 1, 2, 3, 4]

In [47]:
x_train ,x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [48]:
x_train

array([[2, 3],
       [4, 5],
       [0, 1]])

In [49]:
x_test

array([[6, 7],
       [8, 9]])

In [50]:
y_test

[3, 4]

In [51]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)
# model.fit(x_train,y_train)

LinearRegression()

In [52]:
prediction = lin_reg.predict(x_test)

In [53]:
prediction

array([3., 4.])

In [54]:
lin_reg.score(x_test,y_test)

1.0

In [3]:
# def romanToInt():
#     romn = str(input("Enter roman number "))
#     num = 0
#     for i in romn:
#         if i == "I":
#             num+=1
#         elif i == "V":
#             num += 5
#         elif i == "X":
#             num += 10
#         elif i =="L":
#             num += 50
#         elif i =="C":
#             num += 100
#         elif i == "D":
#             num += 500
#         elif i == "M":
#             num+=1000
#         if i < i+1:
#             k = (i+1) - (i)
#             return k
#         return num    


In [1]:
# dict = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}
# for i in romn:
#     if i < i+1:
#         k = (i+1) - i
#     return k
#     else:


# print(i)
#         num+=mydict[i]
#         while romn.index(i) in range(len(romn)):
#             if mydict[i] < mydict[romn[romn.index(i)+1]]:
#                 k = mydict[romn[romn.index(i)+1]] - mydict[i]
#                 num += k
#                 break

In [1]:
# def romanToInt():
#     dict = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}
#     romn = input("Enter roman number ")
#     num = 0
#     for i in romn:
#         while romn.index(i) <= len(romn):
#             if dict[i] < dict[romn[romn.index(i)+1]]:   #.index(dict[i]):
#                 k = dict[romn[romn.index(i)+1]] - dict[i]
#                 num+=k
#         else:
#             num+=dict[i]
#         return num        

In [ ]:
romanToInt()

Enter roman number IV


In [2]:
mydict = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}

jail = "IV"
team =jail[jail.index("I")+1]
print(len(jail))
team

2


'V'

In [10]:
def romanToInt():
    mydict = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}
    roman = input("Enter roman number ")
    num = 0
    for i in roman:
#         num += mydict[i]
        num += mydict[i]
        while roman.index(i) < len(roman)-1:
            if mydict[i] < mydict[roman[roman.index(i)+1]]:
                k = mydict[roman[roman.index(i)+1]] - mydict[i]
                num += k
#             if mydict[i] >= mydict[roman[roman.index(i)+1]]:
                
                break5
#         while roman.index(i) < (len(roman)-1):
#             print(roman.index(i)) 
#             if mydict[i] < mydict[roman[roman.index(i)+1]]:
#                 k = mydict[roman[roman.index(i)+1]] - mydict[i]
#                 num += k
#                 if num not in list(mydict.values()):
#                     break
#                 return "Wrong Input"
            
    return (f"The integer is {num}")

In [11]:
# MCMXCIV

In [12]:
romanToInt()

Enter roman number XI


KeyboardInterrupt: 

In [137]:
# romanToInt()

In [18]:
# romanToInt()

In [19]:
# romanToInt()

In [33]:
# romanToInt()

In [34]:
# def romanToInt():
#     dict = {"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}
#     romn = input("Enter roman number ")
#     num = 0
#     x = [i for i in romn]
#     for n in x:
#         while x.index(n)<=len(x):
#             if dict[x[x.index(n)]] < dict[x[x.index(n)+1]]:
#                 k = dict[x[x.index(n)+1]] - dict[x[x.index(n)]]
#                 num+=k
#                 continue
#                 num+=dict[n]
#         return num

In [35]:
# romanToInt()

In [7]:
mystr = "MCMXCIV"

In [8]:
y = [j for j in mystr]

In [9]:
y

['M', 'C', 'M', 'X', 'C', 'I', 'V']

In [11]:
y.index("M")

0

In [38]:
mystr = "MCMXCIV"
print(len(mystr))
for i in mystr:
    print(mystr)

7
MCMXCIV
MCMXCIV
MCMXCIV
MCMXCIV
MCMXCIV
MCMXCIV
MCMXCIV


In [17]:
values ={
  "I": 1,
  "V": 5,
  "X": 10,
  "L": 50,
  "C": 100,
  "D": 500,
  "M": 1000,
}

def romanToInt(str): 
  total = 0
  i = 0

  while (i < len(str)): 
    s1 = values[str[i]]
    if (i+1 < len(str)): 
        s2 = values[str[i+1]]
        if (s1 >= s2): 
          total = total + s1 
          i = i + 1
        else:   
          total = total - s1 
          i = i + 1
    else: 
      total = total + s1 
      i = i + 1
  return total
  
# Driver code 
print(romanToInt("MCMXCIV")) 


1994
